import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import AppSidebar from "@/layouts/app-sidebar";
import Header from "@/layouts/header";
import Main from "@/layouts/main";

import { getServerSideUIState } from "@/lib/helpers/server-ui-state";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const uiStoreCookie = await getServerSideUIState();
  const sidebarState = uiStoreCookie.sideBarState;

  return (
    <html
      lang={uiStoreCookie.locale}
      dir={uiStoreCookie.locale === "ar" ? "rtl" : "ltr"}
      data-theme={uiStoreCookie.theme}
      data-sidebarstate={sidebarState}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen grid grid-cols-[auto_1fr] grid-rows-[auto_1fr]`}
      >
        <AppSidebar variant="inset" collapsible="icon" className="row-span-2" />
        <Header variant="inset" sticky={true} className="col-start-2" />
        <Main variant="inset" className="col-start-2">
          {children}
        </Main>
      </body>
    </html>
  );
}
